import time
import logging
import re
import json
from typing import List, Dict, Any
from presidio_analyzer import AnalyzerEngine, PatternRecognizer, Pattern, RecognizerRegistry
from presidio_analyzer.nlp_engine import NlpEngineProvider
from .global_pii_regex import PATTERNS, mask_value
from .ner_service import ner_service

logger = logging.getLogger(__name__)

class PIIAnalyzer:
    def __init__(self):
        self.registry = RecognizerRegistry()
        self.registry.load_predefined_recognizers()
        
        # Add custom Indian PII recognizers
        self._add_indian_recognizers()
        
        # Initialize NLP engine for Presidio
        try:
            provider = NlpEngineProvider(nlp_configuration={
                "nlp_engine_name": "spacy",
                "models": [{"lang_code": "en", "model_name": "en_core_web_sm"}]
            })
            self.nlp_engine = provider.create_engine()
            self.analyzer = AnalyzerEngine(nlp_engine=self.nlp_engine, registry=self.registry)
            logger.info("Presidio AnalyzerEngine initialized successfully with spaCy + Indian recognizers")
        except Exception as e:
            logger.error(f"Failed to initialize Presidio NLP engine: {e}")
            self.analyzer = None

        # Self-scan detection markers
        self.system_markers = ["DataSentinel", "Sensitive Data Audit", "Intelligence Engine"]

    def is_self_scan_report(self, text: str) -> bool:
        """Check if the document is a DataSentinel generated report to avoid false positives on metadata"""
        return any(marker in text for marker in self.system_markers)

    def _should_suppress(self, pii_type: str, value: str, context: str, full_text: str) -> bool:
        """Centralized logic to filter out false positives and report metadata"""
        
        # 1. Global Context Checks (for all documents)
        if pii_type == "DOB":
            # Require explicit DOB keywords to avoid matching random dates
            dob_keywords = ["dob", "birth", "born", "date of birth", "d.o.b"]
            if not any(kw in context.lower() for kw in dob_keywords):
                return True

        # 2. Self-Scan Report Suppression (specific to DataSentinel reports)
        if self.is_self_scan_report(full_text):
            # Blacklist system/platform words
            if any(marker.lower() in value.lower() for marker in self.system_markers):
                return True
            
            # Aggressive boilerplate suppression for NAME/ADDRESS/metadata
            report_boilerplate = [
                "report", "summary", "audit", "alignment", "discovery", "inventory", "protection",
                "compliance", "regulatory", "section", "management", "safeguards", "breach", "notification",
                "erasure", "workflow", "active", "required", "review", "compliant", "data", "personal",
                "executive", "risk", "score", "total", "assets", "scanned", "pending", "fiduciary", "principal", "board"
            ]
            
            if pii_type in ["NAME", "ADDRESS", "LOCATION"]:
                # If the value contains any common report word, it's not a real PII person/address
                if any(bp in value.lower() for bp in report_boilerplate):
                    return True
                
                # If length is suspicious
                if len(value) < 4:
                    return True

            # Ignore hex strings or hashes
            if re.search(r'[0-9a-f]{8,}', value.lower()) or re.search(r'[0-9]{5,}', value):
                return True
                
            # Ignore detections near report headers
            header_keywords = ["risk score", "pii types", "audit of", "generated by", "regulatory alignment"]
            if any(kw in context.lower() for kw in header_keywords):
                return True

        return False

    def _add_indian_recognizers(self):
        """Register custom recognizers based on regex patterns from indian_pii_regex.py"""
        scores = {
            "AADHAAR": 0.95, "PAN": 0.90, "MOBILE": 0.75, "EMAIL": 0.85,
            "VOTER_ID": 0.85, "PASSPORT": 0.90, "IFSC": 0.85, "GSTIN": 0.90,
            "UPI": 0.80, "BANK_ACCOUNT": 0.80, "PIN_CODE": 0.60, "DOB": 0.65,
            "DRIVING_LICENSE": 0.85, "CIN": 0.85, "TAN": 0.85
        }
        
        context_words = {
            "AADHAAR": ["aadhaar", "aadhar", "uid", "uidai", "unique id"],
            "PAN": ["pan", "permanent account number", "income tax", "tax id"],
            "UPI": ["upi", "gpay", "phonepe", "vpa", "payment"],
            "IFSC": ["ifsc", "bank code", "neft", "branch"],
            "MOBILE": ["phone", "mobile", "whatsapp", "contact", "cell"],
            "GSTIN": ["gst", "gstin", "tax number", "registration"]
        }

        for name, pattern_obj in PATTERNS.items():
            pattern = Pattern(
                name=f"{name}_pattern",
                regex=pattern_obj.pattern,
                score=scores.get(name, 0.7)
            )
            
            recognizer = PatternRecognizer(
                supported_entity=name,
                patterns=[pattern],
                context=context_words.get(name, [])
            )
            
            self.registry.add_recognizer(recognizer)

    def analyze(self, text: str, source_type: str = "file") -> Dict[str, Any]:
        start_time = time.time()
        
        if not text or not text.strip():
            return {"detections": [], "total_found": 0, "processing_time_ms": 0}

        all_detections = []
        seen_spans = set()

        # Step 1: Use Presidio
        if self.analyzer:
            try:
                # Entities to detect
                entities = list(PATTERNS.keys()) + ["PERSON", "EMAIL_ADDRESS", "PHONE_NUMBER", "LOCATION", "DATE_TIME"]
                results = self.analyzer.analyze(text=text, entities=entities, language="en", score_threshold=0.4)
                
                # Normalize types to backend enums/readable names
                type_map = {
                    "PERSON": "NAME", "EMAIL_ADDRESS": "EMAIL", "PHONE_NUMBER": "MOBILE",
                    "LOCATION": "ADDRESS", "DATE_TIME": "DOB"
                }

                for r in results:
                    span_key = (r.start, r.end)
                    if span_key not in seen_spans:
                        seen_spans.add(span_key)
                        pii_type = type_map.get(r.entity_type, r.entity_type)
                        value = text[r.start:r.end]
                        context = text[max(0, r.start-60):min(len(text), r.end+60)]
                        
                        if self._should_suppress(pii_type, value, context, text):
                            continue

                        all_detections.append({
                            "pii_type": pii_type,
                            "masked_value": mask_value(value, pii_type),
                            "confidence": round(r.score, 2),
                            "start": r.start,
                            "end": r.end,
                            "language": "en",
                            "context": context
                        })
            except Exception as e:
                logger.error(f"Presidio analysis error: {e}")

        # Step 2: spaCy Fallback
        try:
            ner_results = ner_service.detect_entities(text)
            for ent in ner_results:
                span_key = (ent["start"], ent["end"])
                if span_key not in seen_spans:
                    seen_spans.add(span_key)
                    pii_type = ent["pii_type"]
                    value = ent['text']
                    context = text[max(0, ent["start"]-60):min(len(text), ent["end"]+60)]

                    if self._should_suppress(pii_type, value, context, text):
                        continue

                    all_detections.append({
                        "pii_type": pii_type,
                        "masked_value": mask_value(value, pii_type),
                        "confidence": ent["confidence"],
                        "start": ent["start"],
                        "end": ent["end"],
                        "language": "en",
                        "context": context
                    })
        except Exception as e:
            logger.error(f"Fallback NER error: {e}")

        elapsed_ms = int((time.time() - start_time) * 1000)
        return {
            "detections": all_detections,
            "total_found": len(all_detections),
            "processing_time_ms": elapsed_ms
        }

# Singleton
analyzer = PIIAnalyzer()

def detect(text: str, source_type: str = "file") -> Dict[str, Any]:
    return analyzer.analyze(text, source_type)
